name: Rust

on: 
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy?'     
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-dev:
    if: github.event.inputs.deploy == 'yes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add wallet
        run: echo $DEVNET_DEV_WALLET > id.json
        env:
          DEVNET_DEV_WALLET: ${{ secrets.DEVNET_DEV_WALLET }}
      - name: Add Program Keypair
        run: echo $ORACLE_PROGRAM_KEYPAIR_DEV > program-keypair.json
        env:
          ORACLE_PROGRAM_KEYPAIR_DEV: ${{ secrets.ORACLE_PROGRAM_KEYPAIR_DEV }}
      - name: Deploy to Devnet
        run: docker build -f Dockerfile.ci -t ci . && docker run ci sh ./.ci/deploy-dev.sh
