name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add wallet
        run: echo $WALLET > id.json
        env:
          WALLET: ${{ secrets.DEVNET_DEV_WALLET }}
      - name: Add Program Keypair
        run: echo $PROGRAM_KEYPAIR > program-keypair.json
        env:
          PROGRAM_KEYPAIR: ${{ secrets.PROGRAM_KEYPAIR_DEV }}
      - name: Anchor Tests
        run: docker build -f Dockerfile.ci -t ci . && docker run ci sh ./.ci/tests.sh
  deploy-dev:
    needs: tests
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add wallet
        run: echo $DEVNET_DEV_WALLET > id.json
        env:
          DEVNET_DEV_WALLET: ${{ secrets.DEVNET_DEV_WALLET }}
      - name: Add Program Keypair
        run: echo $PROGRAM_KEYPAIR > program-keypair.json
        env:
          PROGRAM_KEYPAIR: ${{ secrets.PROGRAM_KEYPAIR_DEV }}
      - name: Deploy to Devnet
        run: docker build -f Dockerfile.ci -t ci . && docker run ci sh ./.ci/deploy-dev.sh
